# Generated by Django 4.0.3 on 2023-03-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relative', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relativelist',
            old_name='users',
            new_name='user',
        ),
    ]
