# Generated by Django 4.0.3 on 2023-03-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relative', '0002_rename_users_relativelist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relativelist',
            old_name='user',
            new_name='users',
        ),
    ]
